language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: M4a5lyfJqjmM2aVcGBJvqohz2c3mRPYNjcgytnXKuVLMo7NXKitPBOZTtEiGoPYfy4YOyNcUTby3in4RSW6GxLNgnh0UV+SzH+Y6DAvv+vKmj645+xfmoB+kkdGpmKDBTL3Vjs1Avx+s0pmpXyei+S4IyXWGOXr35swxMVaP/g4qKvkIKE+shXnvY6lER9JFGCWczKRt7ELnVGCGoUFwspeR1zaJuDWug2KJ6XlsP2syGLSC4GsXDmI5wfTq3M6mjqgyIgC8npyXXLXJuJexsJzBFFz3e5wFr8lGcY6DQx6R8vtn4Ui88ckuRcFcYS2FWQEkATrgi4WteMtrd9/VGKwt79AlTtNJ+cCq+CDWMXSSQU7u2937xDKtogqKY7sgfutk9mBYMpGU473uNDg81uT7/2g3E017bG7afVknTRX1SnyQI6jmN7w8Asakacm17g/j+FL2VN5MPa+JeQwAU5LtFghuwJQ5dHTjaG93b5L70QQHeVvdbQEVY+chtsoP0TrHqzaqD9G7raLc8qLevKrt/hgJNq4IqYTySMukXNESyhOPrJhwTFBT13DKlEf833DqelxkxvE7U31qaTTxBhF0ke/08cxpVCy2PIsAQvBKodL/sIQIBfBALILBzgaERf4WhCqGKpXTAgDAa5TXyb23nXdL7EEkZ++z8WRLAmY=
  - secure: LaVm/T6LOmSzNN5WV8GNPdZxSOmoVafefFsBbF+waUSeYgxebLB84rfWvmPcx3hUX8stMYkJ3xzqe/3YFKrxNpfZ5AR60djDnE2+L6dfYQD0i21dlZmhx6gcRmm0zrYodD8v5YceQiDhebUAiUPnleF42puMcvhl0Q4ikg1Z6a54C6r/AEz/0+l2xnZQ27es+m2CcNQZsId6zh0rm0usKF526AWaNGIefAuYTj30BI2kZ8CpqThMdAtPDXQ8Uwzb6KRXyzuduAXuuhG8duZcLDUB+wG3ErOUGfqdpPv4F/lW4FCmpZxmG8JTGoBhvjChoXqzPZgKt5BSMihn5QiS0MiHVaxyGG+Uu4sYCPVj/8e3LY5jLyDMdnA2puWOHHVINUiPKnKcUCxMsC/VFDvmnVv95r82jmQFYgbpq8w6Q2rB+MWVkxh8V31pKwINRwaqrw3ZUFMAOXASM5f7nf+hMJh6Xxq3BWH43N5l/mbn1SMWY6RTdh2EfhQMV/NQFySRqDnJp9lD8IGVmAhDaNCVw/mY3sdZi5gdhk1BueOFbzi+fEKUu1iPpLCoJijAIKSIXmnxyumPRn50lP1aTkHwvfPGrul0ABDhTjCmRg/n4x91tAAmj2eKUKRsH5YfqM61arekwVEzcSN+D9XOB9ccZhBka+d5qnXc1oAT8nkuC1I=
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
dist: trusty
